
name: Integration 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy: 
      matrix:
        run-config:
          - { scheme: 'hexagon (macOS)', destination: 'platform=macOS'}
          - { scheme: 'hexagon (iOS)', destination: 'platform=iOS Simulator,OS=15.2,name=iPhone 13' }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Available Applications
        run: ls /Applications

      - name: Switch to Xcode 13
        run: sudo xcode-select -s /Applications/Xcode_13.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings
        
      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Show Available Destinations
        env:
          scheme: ${{ matrix.run-config['scheme'] }}    
        run: xcodebuild -scheme ${scheme} -showdestinations


