
name: Integration 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11
    strategy: 
      matrix:
        xcode: ["13.2.1"]
        run-config:
          - { xcodeproj: 'hexagon.xcodeproj', scheme: 'hexagon (macOS)', destination: 'platform=macOS'}
          - { xcodeproj: 'hexagon.xcodeproj', scheme: 'hexagon (iOS)', destination: 'platform=iOS Simulator,OS=15.2,name=iPhone 13' }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Available Applications
        run: ls /Applications

      - name: Switch to Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Show Build Version
        working-directory: ./apple
        run: xcodebuild -version

      - name: Show Build SDK
        working-directory: ./apple
        run: xcodebuild -showsdks

      - name: Show Available Destinations
        env:
          scheme: ${{ matrix.run-config['scheme'] }}
        working-directory: ./apple
        run: xcodebuild -scheme "${scheme}" -showdestinations

      - name: Show Build Settings
        working-directory: ./apple
        run: xcodebuild -showBuildSettings

      - name: Build
        working-directory: ./apple
        run: xcodebuild build-for-testing -project ${{ matrix.run-config['xcodeproj'] }} -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}'

      - name: Test
        working-directory: ./apple
        run: xcodebuild test-without-building -project ${{ matrix.run-config['xcodeproj'] }} -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}'


